version: '3.3'
services:
  galactic01:
    image: cm2network/squad:latest
    ports:
     - 7787:7787/udp
     - 7788:7788/udp
     - 21114:21114
     - 21114:21114/udp
     - 27165:27165
     - 27165:27165/udp
     - 27166:27166
     - 27166:27166/udp
    volumes:
     - /var/squad/data/:/home/steam/squad-dedicated/
    networks:
     - net
    logging:
      driver: json-file
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '4.0'
networks:
  net:
    driver: overlay
